App\Entity\Libro:
  attributes:
    id:
      groups: ['libro']
    title:
      groups: ['libro']
    image:
      groups: ['libro']
    categories:
      groups: ['libro']
#    authors:
#      groups: ['libro']
#    description:
#      groups: ['libro']
#    score:
#      groups: ['libro']
#    readAtAsString:
#      groups: ['libro']
#      serialized_name: readAt
#    createdAt:
#      groups: ['libro']
